### PRODUCTOS
GET http://127.0.0.1:8000/zapatos/prod_all

###
GET http://127.0.0.1:8000/zapatos/prod/1

###
POST http://127.0.0.1:8000/zapatos/prod_add
Content-Type: application/json

{
  "nombre": "Air Jordan 1",
  "marca": "Nike",
  "talla": "43",
  "color": "Rojo/Negro",
  "precio": 520000,
  "stock": 5,
  "id_proveedor": 1
}

###
PUT http://127.0.0.1:8000/zapatos/prod_update/1
Content-Type: application/json

{
  "nombre": "Air Jordan 1",
  "marca": "Nike",
  "talla": "43",
  "color": "Rojo/Negro",
  "precio": 550000,
  "stock": 8,
  "id_proveedor": 1
}

###
DELETE http://127.0.0.1:8000/zapatos/prod_borrar/1

###
### PROVEEDORES
GET http://127.0.0.1:8000/zapatos/prov_all

###
GET http://127.0.0.1:8000/zapatos/prov/1

###
POST http://127.0.0.1:8000/zapatos/prov_add
Content-Type: application/json

{
  "nombre": "Puma Latam",
  "contacto": "Jorge Ruiz",
  "telefono": "3009998877",
  "email": "ventas@puma.com",
  "ciudad": "Bogotá",
  "pais": "Colombia"
}

###
PUT http://127.0.0.1:8000/zapatos/prov_update/1
Content-Type: application/json

{
  "nombre": "Nike Colombia S.A.",
  "contacto": "Carlos Mejía",
  "telefono": "3001234567",
  "email": "ventas@nike.com",
  "ciudad": "Bogotá",
  "pais": "Colombia"
}

###
DELETE http://127.0.0.1:8000/zapatos/prov_borrar/6

###
### CLIENTES
GET http://127.0.0.1:8000/zapatos/cli_all

###
GET http://127.0.0.1:8000/zapatos/cli/1

###
POST http://127.0.0.1:8000/zapatos/cli_add
Content-Type: application/json

{
  "nombre": "Laura Ospina",
  "telefono": "3177776655",
  "email": "laura@gmail.com",
  "ciudad": "Mosquera"
}

###
PUT http://127.0.0.1:8000/zapatos/cli_update/1
Content-Type: application/json

{
  "nombre": "Juan Pérez",
  "telefono": "3101112233",
  "email": "juan@gmail.com",
  "ciudad": "Bogotá"
}

###
DELETE http://127.0.0.1:8000/zapatos/cli_borrar/11

###
### VENTAS
GET http://127.0.0.1:8000/zapatos/ven_all

###
GET http://127.0.0.1:8000/zapatos/ven/1

###
POST http://127.0.0.1:8000/zapatos/ven_add
Content-Type: application/json

{
  "fecha": "2026-04-03",
  "total": 350000,
  "id_cliente": 1,
  "id_usuario": 1
}

###
PUT http://127.0.0.1:8000/zapatos/ven_update/1
Content-Type: application/json

{
  "fecha": "2026-04-03",
  "total": 700000,
  "id_cliente": 1,
  "id_usuario": 1
}

###
DELETE http://127.0.0.1:8000/zapatos/ven_borrar/6

###
### USUARIOS
GET http://127.0.0.1:8000/zapatos/usr_all

###
POST http://127.0.0.1:8000/zapatos/usr_add
Content-Type: application/json

{
  "nombre": "Carlos Empleado",
  "email": "carlos@gmail.com",
  "contrasena": "1234",
  "rol": "empleado"
}